# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27d847833e53e7922717d1f8bddab4fc6ed5a494750e7caddf62972458db46d69f189f1fac6fa81c42ebf3e3f9f601d8ba84d4d66394d9fe7a9e485f06a7b671

test:
  secret_key_base: 5010a1a0a7b35c8ddeece9e23cd6c23dff6c9bf7a2f31de6c8b360f09aeee9a146818507452c455bd9ab95e2987d2ec7822bb6cca61545b72c728cac135de49a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
